#cloud-config

#apt_update: true
#apt_upgrade: true

packages:
 - python3-pip
 - build-essential
 - rabbitmq-server
 - nfs-kernel-server
 - avahi-daemon 
 - avahi-discover
 - avahi-utils
 - libnss-mdns
 - mdns-scan

byobu_default: system 

# Users/groups modules does not work?! Using runcmd instead.
#groups:
# - ubuntu: [root, sys]
# - airfoil
#
#users:
# - default
# - name: airfoil
#   gecos: Airfoil user
#   groups: airfoil
#   system: true
#   sudo: false
# - name: admin
#   gecos: Admin user
#   groups: ubuntu, airfoil
#   lock-passwd: false
#   sudo: ALL=(ALL) NOPASSWD:ALL
#   shell: /bin/bash
#   ssh_authorized_keys:
#    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnb/qBTnmXiU3T4yBLgNr6p2LPbspEf1wMqbyDmjoqsEF4vWmfeMeZMUrdpwjcBvlpyczyG+UQfacOLzgK3OwXXMesiCn/4HDSmiJbY5+Z3NgZAKZP73b6dMxpbjr5RPuHWMQfm6jBqaODuA/lRs7iOTDczYaacmERsF7wT3jSHjRjXHCTZX2y0+XK43mFUGyA1NGmxvwbmA47OhC3hkcpjxtT15lKlWChgkX4DyCKJOHK5c2IfAOAX1pT+o1K5/QQHCtdTHqbi9lMwTIgKUTBQFe1CgRO1dyojOv9/gYT2QPv+B7/j4IeOsynHav2WQpM9dinKqHeb4iLzF6XqFxv mats@ugh

write_files:
 - path: /etc/exports
   content: |
     /home/ubuntu/acc-airfoil/data  192.168.2.0/24(ro,sync,no_subtree_check)

runcmd:

# Setup ssh keys
 - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnb/qBTnmXiU3T4yBLgNr6p2LPbspEf1wMqbyDmjoqsEF4vWmfeMeZMUrdpwjcBvlpyczyG+UQfacOLzgK3OwXXMesiCn/4HDSmiJbY5+Z3NgZAKZP73b6dMxpbjr5RPuHWMQfm6jBqaODuA/lRs7iOTDczYaacmERsF7wT3jSHjRjXHCTZX2y0+XK43mFUGyA1NGmxvwbmA47OhC3hkcpjxtT15lKlWChgkX4DyCKJOHK5c2IfAOAX1pT+o1K5/QQHCtdTHqbi9lMwTIgKUTBQFe1CgRO1dyojOv9/gYT2QPv+B7/j4IeOsynHav2WQpM9dinKqHeb4iLzF6XqFxv mats@ugh" >> /home/ubuntu/.ssh/authorized_keys

# Create group and user airfoil
 - groupadd airfoil
 - useradd -u 1001 -g airfoil airfoil

# Add ubuntu to group airfoil
 - usermod -a -G airfoil ubuntu

# Install packages
 - pip3 install Flask
 - pip3 install -Iv celery==4.4.7
 - pip3 install flower

 - rabbitmqctl add_user worker fnurkgurk
 - rabbitmqctl add_vhost twhost
 - rabbitmqctl set_user_tags worker worker
 - rabbitmqctl set_permissions -p twhost worker ".*" ".*" ".*"

 - cd /home/ubuntu
 - git clone https://github.com/farbro/acc-airfoil.git
 - cd acc-airfoil
 - git checkout secure

 # Set priveleges
 - chown -R ubuntu:airfoil /home/ubuntu/acc-airfoil 
 - chmod -R 644 /home/ubuntu/acc-airfoil 
 - chmod 755 /home/ubuntu/acc-airfoil 

# Configure NFS share
 - mkdir data
 - chown nobody:nogroup data
 - chmod 777 data
 - exportfs -a
 - sytemctl restart nfs-kernel-server
 
# Install flower service
 - cp /home/ubuntu/acc-airfoil/deploy/services/airfoil-flower.service /etc/systemd/service
 - systemctl start airfoil-flower
 - systemctl enable airfoil-flower

# Install airfoil app service
 - cp /home/ubuntu/acc-airfoil/deploy/services/airfoil-main.service /etc/systemd/service
 - systemctl start airfoil-main
 - systemctl enable airfoil-main
