#cloud-config
apt_update: true
apt_upgrade: true

packages:
 - python3-pip
 - build-essential
 - rabbitmq-server
 - nfs-common
 - libnss-mdns
 - mdns-scan

byobu_default: system 

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "mtu": 1400
      } 

runcmd:
# Setup ssh keys
 - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnb/qBTnmXiU3T4yBLgNr6p2LPbspEf1wMqbyDmjoqsEF4vWmfeMeZMUrdpwjcBvlpyczyG+UQfacOLzgK3OwXXMesiCn/4HDSmiJbY5+Z3NgZAKZP73b6dMxpbjr5RPuHWMQfm6jBqaODuA/lRs7iOTDczYaacmERsF7wT3jSHjRjXHCTZX2y0+XK43mFUGyA1NGmxvwbmA47OhC3hkcpjxtT15lKlWChgkX4DyCKJOHK5c2IfAOAX1pT+o1K5/QQHCtdTHqbi9lMwTIgKUTBQFe1CgRO1dyojOv9/gYT2QPv+B7/j4IeOsynHav2WQpM9dinKqHeb4iLzF6XqFxv mats@ugh" >> /home/ubuntu/.ssh/authorized_keys
 - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDjYoFMqsSvoqHZqNtAQ9pcmtvbflbAzwUZJHmqR6Da4EgBUopJGS81eeUVrEAvFixH1tTbn0lO7A0NRGeMENuu7++gk732AaZCHS2psE8q1amrLNbcX+JZXuliJl/i1tPN6NOzKWR+I3/HhxsY4fyKkwaUuT4C5FXjxZhmvOoodgx7uMyoC206usQOYqIlYrAeAaIeJSErEHkqMcr4sbLviabV0yOvP+obwC6oCPOIFHtJbdVy+DaMih1aW0+UxbFkjDs+7yltzS6mBgwhr485dLCjqqKtbPA7usE7aNgwsKCenGjl7O+o12WP671BtYC3t36qCyJJA6WCOtDu5N1 Generated-by-Nova" >> /home/ubuntu/.ssh/authorized_keys

# Create group and user airfoil
 - groupadd -g 1001 airfoil
 - useradd -u 1001 -G airfoil,docker airfoil

# Add ubuntu to group airfoil
 - usermod -a -G airfoil ubuntu


# Install packages
 - pip3 install Flask celery
 - pip3 install -Iv celery==4.4.7
 - sudo apt install python-numpy
 
 - cd /home/ubuntu
 - git clone https://github.com/farbro/acc-airfoil.git
 - cd acc-airfoil
 - cd ..

 # TODO install airfoil docker (below)
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo apt-get install software-properties-common
 - sudo apt update
 - sudo apt upgrade
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 - sudo apt-get update
 - apt-cache policy docker-ce
 - sudo apt-get install -y docker-ce
 
 # deploy fenics container
 - sudo docker run --name fenics_cont -td -v $(pwd):/home/fenics/shared -w /home/fenics/shared quay.io/fenicsproject/stable:current

 - sudo docker cp acc-airfoil/murtazo fenics_cont:/home/fenics/shared/.

 # Set priveleges
 - chown -R ubuntu:airfoil /home/ubuntu/acc-airfoil 
 - chmod -R 644 /home/ubuntu/acc-airfoil 
 - find chmod 755 /home/ubuntu/acc-airfoil 

# Mount NFS dir
 - cd /home/ubuntu/acc-airfoil
 - mkdir data
 - chown ubuntu:airfoil data
 - chmod 770 data
 - mount g2-test-main.local:/home/ubuntu/acc-airfoil/data data

# Install worker service
 - cp /home/ubuntu/acc-airfoil/deploy/services/airfoil-worker.service /etc/systemd/system/
 - systemctl start airfoil-worker
 - systemctl enable airfoil-worker
